spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      db-type: mysql
      initialSize: 1
      minIdle: 3
      maxActive: 20
  mvc:
    view:
      suffix: .jsp
    static-path-pattern: /static/**
pagehelper:
  helper-dialect: mysql #不同的数据库分页语句可能不一样,
  params: count=countsql
  reasonable: true
  support-methods-arguments: true
server:
  servlet:
    session:
      cookie:
        http-only: false
  tomcat:
    uri-encoding: utf-8
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl